#
#Dependencies
markdown:            redcarpet
highlighter:         pygments


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Woowen
tagline:             'You can do anything you set your mind to, man'
description:         '明证本心,明心见性'
url:                 http://www.woowen.com
baseurl:             /
paginate:            5
github:				 https://github.com/woooowen
rss:				 /atom.xml
# Custom vars
version:             1.5.0
